### ISSUE TITLE
Add functionality to upgrade and downgrade resolution

### ISSUE THREAD

**Issue by fjaviersanchez** [LSSTDESC/healsparse#1]
A nice (and needed functionality) is to increase and decrease the resolution of the `HealSparse` objects. I'll start this at some point this week (probably later today or tomorrow).

**Comment by fjaviersanchez** [comment]
Downgrade closed by #10. Upgrade not yet available.

**Comment by erykoff** [comment]
@fjaviersanchez I'm not sure of the use case of upgrading resolution?  Is this something we still want to implement?

**Comment by fjaviersanchez** [comment]
I was mentioning this because in `healpy` you have `ud_grade` that can increase the resolution. What this does is essentially mean interpolation, so in the nest scheme I think it would just pass the same value to the children pixels. I'm not sure that there are any applications where we need this so I think it's safe to close this.
