### ISSUE TITLE
Warn against poor performance with very large nside_coverage

### ISSUE THREAD

**Issue by erykoff** [LSSTDESC/healsparse#101]
@rgruendl has pointed out that things did not work well when he (as a novice user) had tried `nside_coverage=1024`.  And in fact, this is not surprising!

In my usage I have not found anything greater than `nside_coverage>128` to be useful.

I will do a couple of benchmark tests to confirm where things really do start struggling, and add a warning if a higher `nside_coverage` is specified to protect against these sorts of mistakes.

**Comment by fjaviersanchez** [comment]
Closed by #103
