### ISSUE TITLE
error for bum inputs

### ISSUE THREAD

**Issue by beckermr** [LSSTDESC/healsparse#104]
@erykoff mentioned to me it might be nice to provide a more sane error if a dumb user like me feeds an array in for a scalar for various things (e.g., `healsparse.Circle`).

**Comment by erykoff** [comment]
Currently this will give a cryptic `healpy` error if you give an array of circle radii, but we can do better!

**Comment by fjaviersanchez** [comment]
Do we want to support the case where if lists of `ra, dec, radius` of the same size are passed, we generate a list of `Circle` objects?

**Comment by beckermr** [comment]
That seems far too fancy. Python zip was created for a reason.

**Comment by beckermr** [comment]
The actual reason not to is idioms. Instantiating an object and getting back a list of those objects is unexpected. 

If you want to do this, add a class method that is called from_iterable or something?

**Comment by fjaviersanchez** [comment]
Thanks @beckermr! I think that's a good point. I'll stick to just clarify the docstrings and the error message.

**Comment by fjaviersanchez** [comment]
I addressed this in #108. Please @beckermr feel free to reopen if you feel that the solution implemented is not sufficient. Thanks!
