### ISSUE TITLE
Add information on quick visualization to the documentation

### ISSUE THREAD

**Issue by erykoff** [LSSTDESC/healsparse#105]
I regularly use the following pattern for the quick visualization of a healsparse map:

```
vpix, ra, dec = hsp_map.valid_pixels_pos(return_pixels=True)
plt.hexbin(ra, dec, C=hsp_map[vpix])
plt.colorbar()
plt.show()
```

This isn't necessarily obvious, and doesn't make things super fancy, but it does work in a pinch and is helpful to know.  This should be added to the documentation in a short section on visualization.

When we are comfortable with `cartosky` we can also recommend that as a way to do more sophisticated visualization.

**Comment by fjaviersanchez** [comment]
closed by #109
