### ISSUE TITLE
Add "upgrade" option for maps

### ISSUE THREAD

**Issue by erykoff** [LSSTDESC/healsparse#119]
@esheldon has requested the ability to _increase_ the resolution of a map.  While this can be worked around (by doing pixel lookups, since healpix pixels are hierarchical any lower res pixel completely covers all the higher res pixels), for some uses (you have a low res footprint map and want to seamlessly combine it with a higher res map) it would be convenient.

This would be accomplished by duplicating pixel values in each lower res pixel.

At the same time, I think it would be convenient to add an `nside` option to `get_values_pix()` which would allow easier lookups when you have pixel values at a different resolution.

**Comment by esheldon** [comment]
works in my tests

**Comment by wmwv** [comment]
Was this completed resolved by #120 ?
