### ISSUE TITLE
Update docs of `hsp.read`

### ISSUE THREAD

**Issue by fjaviersanchez** [LSSTDESC/healsparse#126]
@nsevilla reported that in the docs we have `nside_coverage` as input keyword for `hsp.read`, but this is not the case anymore.

**Comment by fjaviersanchez** [comment]
Here's the traceback: 
```
hs.HealSparseMap.read('/pool/cosmo01_data1/des/y6_sp_maps/mangle_maps/SPmaps/band_g/y6a2_g_o.4096_t.32768_AIRMASS.WMEAN_EQU.fits.fz', nside_coverage=32)

TypeError: read() got an unexpected keyword argument 'nside_coverage'
```

**Comment by erykoff** [comment]
That should work. Is he running an old version?

**Comment by fjaviersanchez** [comment]
Hmm, not sure. @nsevilla, what version are you running? 

Yeah, I was checking the code, and the keyword is there in the master branch, as you point out.

**Comment by nsevilla** [comment]
Indeed, that was the case, can close this.
