### ISSUE TITLE
print of map uses huge memory

### ISSUE THREAD

**Issue by esheldon** [LSSTDESC/healsparse#154]
This uses more memory than 12G (I don't know how much because it was killed).  Maybe in a case like this it is better to just print some summary information about the map

```
[esheldon@forest y6-healsparse] ipython
[nav] In [1]: import healsparse
[nav] In [2]: hmap = healsparse.HealSparseMap.read('y6-combined-hleda-gaiafull-des-stars-hsmap131k-mdet-v2.hsp')
[ins] In [3]: hmap
```

**Comment by erykoff** [comment]
Okay, can replicate locally.  I will investigate.
