### ISSUE TITLE
Add support for gnomonic projections.

### ISSUE THREAD

**Issue by slosar** [LSSTDESC/healsparse#18]
This is a feature request. Might be useful to have an equivalent of gnomview, effectively projecting the map onto a flat sky approximation, returning two 2D arrays with the map and mask around some desired center. I think healpix already has the infrastructural functions required to make this work. This would allow one to project out a small patch, for example to cross-correlate some small footprint survey with LSST data or to simply visualize a patch. But again, this should be very low priority.

**Comment by fjaviersanchez** [comment]
I think that, for now, I'm going to go with `matplotlib`'s projections and create some visualization functions.

**Comment by kadrlica** [comment]
I suggest separating the base healsparse functionality from more complex plotting functionality. I'm hoping that [`cartosky`](https://github.com/kadrlica/cartosky) can help satisfy many plotting requirements by interfacing `healsparse` with `cartopy` (i.e., this list of [cartopy projections](https://scitools.org.uk/cartopy/docs/latest/crs/projections.html)). I will note that cartopy has a long way to go...

**Comment by erykoff** [comment]
We have decided that plotting will not be a part of `healsparse`.  But many updates have been made to `healsparse` to make plotting (with, e.g., `cartosky`) easier.
