### ISSUE TITLE
generate masks from circles and polygons

### ISSUE THREAD

**Issue by esheldon** [LSSTDESC/healsparse#23]
this should be straighforward using `query_disc` and `query_polygon`

**Comment by esheldon** [comment]
I'll implement it, can you make me a collaborator @erykoff ?

**Comment by erykoff** [comment]
Done.  And I just did a quick check on my workstation and a 0.5 arcmin `query_disc` at nside=65536 takes 70 microseconds in nest (interestingly, this is 3x longer than ring).
