### ISSUE TITLE
Writing of maps does not round-trip for high nside maps

### ISSUE THREAD

**Issue by erykoff** [LSSTDESC/healsparse#31]
Due to a bug in `fitsio`, see https://github.com/esheldon/fitsio/issues/256, the map does not round-trip properly when nside is large enough that pixel indices are 64-bit integers.

When that is fixed, there will be a minimum version of `fitsio` required, or we change the file format to save the coverage map as an array in a binary table instead of as an image.

**Comment by esheldon** [comment]
solved by fitsio 1.0.5
