### ISSUE TITLE
make_circles 

### ISSUE THREAD

**Issue by saharallam** [LSSTDESC/healsparse#39]
using HealSparse tutorial I got the following error:
file python2.7/site-packages/healsparse/geom.py 
line 6
    def make_circles(*, ra, dec, radius, value):
                      ^
SyntaxError: invalid syntax
Thanks!

**Comment by fjaviersanchez** [comment]
Hi @saharallam! I can reproduce this error in python 2.7 and it's a python 2.x vs python 3.x issue. Unfortunately, we will not be supporting python 2.x. You can try to eliminate the `*` in the function definitions as a workaround. I'm pinging @erykoff in case he has some other suggestions.
