### ISSUE TITLE
Create a function to query position of sparse map

### ISSUE THREAD

**Issue by fjaviersanchez** [LSSTDESC/healsparse#44]
I have received some requests for functionality to directly get the positions of valid pixels in order to be plotted with some routine. This can be achieved by using the pixel number of the valid pixels and the `healpy.ang2pix` routine. 

@erykoff, do you think this would be a useful feature? Would we want to return all pixels or given the index of the healsparse map, get the ra, dec?

**Comment by erykoff** [comment]
The original plan would be to do something like `ra, dec = hp.pix2ang(hsp.nside_sparse, hsp.valid_pixels, lonlat=True)`, but I could see that this would be common enough to add a `def valid_pixels_pos(self, lonlat=False)` method that just does this.

**Comment by fjaviersanchez** [comment]
Closed by #45
