### ISSUE TITLE
Trouble installing and running healsparse 1.1.1 in DM v19 environment

### ISSUE THREAD

**Issue by heather999** [LSSTDESC/healsparse#58]
This is ultimately impacting my ability to install and run supreme, but the problem seems to be due to healsparse. I grabbed lsstsqre/centos:7-stack-lsst_distrib-v19_0_0 and in the container I do:
```
source loadLSST.bash
pip install healsparse
python -c "import healsparse"
```
and I end up with an error:
```
ImportError: /lib64/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by /opt/lsst/software/stack/python/miniconda3-4.7.10/envs/lsst-scipipe-4d7b902/lib/python3.7/site-packages/scipy/sparse/_sparsetools.cpython-37m-x86_64-linux-gnu.so)
```
I see you're testing supreme with DM v19... though looking at the healsparse GH workflow, I think it's being testing with scipy 1.4.1 which isn't in DM v19 (maybe I'm not looking at all the workflow variants).  If I again start with the DM v19 docker image and install scipy 1.4.1, then healsparse, I still get a similar, though slightly different, error:
```
ImportError: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /opt/lsst/software/stack/python/miniconda3-4.7.10/envs/lsst-scipipe-4d7b902/lib/python3.7/site-packages/scipy/_lib/_uarray/_uarray.cpython-37m-x86_64-linux-gnu.so)
```
Any ideas what might be going wrong?

**Comment by heather999** [comment]
actually.. I think this may be an issue with `healpy` as the error also occurs if I do:
`python -c "import healpy"`  
I have healpy 1.13.0

**Comment by heather999** [comment]
Poking into the most recent [github action for supreme](https://pipelines.actions.githubusercontent.com/3rEI05xpErcbGyG5Nei8EXa2r13OYRJ8mK6Vfipi1TiOAzhn26/_apis/pipelines/1/runs/60/signedlogcontent/3?urlExpires=2020-06-05T01%3A12%3A13.0012302Z&urlSigningMethod=HMACV1&urlSignature=XK3BlnhD57V8yJyG1fYFmnokC2bACnPN%2BXY5OEdcCfM%3D)
I noticed it used `healpy==1.10.3`  Constraining the install to that version appears to work, and then I can successfully install healsparse and supreme.  :)

**Comment by erykoff** [comment]
Ah, I found the issue.  If you're installing `healsparse` with the Rubin stack, then you must to _first_ do `setup lsst_distrib` before `pip install healsparse` in order to match all the correct dependencies.
