### ISSUE TITLE
Add option to "or" overlapping pixels when concatenating integer maps

### ISSUE THREAD

**Issue by erykoff** [LSSTDESC/healsparse#61]
Currently, when concatenating maps with `cat_healsparse_files` the only option is to overwrite values when two maps have the same pixel defined.  When concatenating integer mask maps, it is often useful to be able to "or" together the overlaps (which allows, for example, efficient parallelization of rendering of star masks).

**Comment by fjaviersanchez** [comment]
Closed by #88
