### ISSUE TITLE
Add nest argument to generate_healpix_map

### ISSUE THREAD

**Issue by kadrlica** [LSSTDESC/healsparse#67]
It'd be nice to be able to get the healpix map back in RING format so that it can be fed directly into healpy. I'm suggesting an optional `nest` argument to [generate_healpix_map](https://github.com/LSSTDESC/healsparse/blob/8b4054db0a90f27fbf7f281a94eec241fb1cc301/healsparse/healSparseMap.py#L1021).

**Comment by erykoff** [comment]
We can do this, yes. But healpy will work with nest maps you just need to use the keyword, right?

**Comment by kadrlica** [comment]
Yeah, or you can reorder. The question is whether we want to fight the healpy ring convention, or give users what they are used to working with.

Actually, updating this... I'm not suggesting that the default should be RING, just that `nest` seems like a basic option that should come with most functions.

**Comment by erykoff** [comment]
...or recommend that you not convert healsparse maps to healpy because in many use cases that will blow up your memory.

(Though it's convenient after a degrade).  

Anyway, I agree that we should add this.

**Comment by erykoff** [comment]
Added with #69 .
