### ISSUE TITLE
Trying to degrade a map below nside_coverage gives unhelpful error.

### ISSUE THREAD

**Issue by erykoff** [LSSTDESC/healsparse#99]
Right now if you try to run, e.g., `m.degrade(8)` on a map with `nside_coverage=32`, then you get an unhelpful error `ValueError: cannot reshape array`.  This should either (a) raise with a more helpful error, or (possibly; this might be slow and use too much memory?) (b) remake the map with lower nside_coverage and then degrade.

**Comment by fjaviersanchez** [comment]
Closed by #100
